# Generated by Django 3.1.4 on 2020-12-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201228_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprofile',
            name='background',
            field=models.ImageField(default='profile/photos/default/profile_photo_default.jpg', upload_to='profile/photos/background/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='modelprofile',
            name='avatar',
            field=models.ImageField(default='profile/photos/default/profile_photo_default.jpg', upload_to='profile/photos/avatar/%Y/%m/%d/'),
        ),
    ]
