# Generated by Django 3.1.4 on 2020-12-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='img',
            field=models.ImageField(blank=True, upload_to='post/%Y/%m/%d/'),
        ),
    ]
