# Generated by Django 3.1.4 on 2020-12-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20201205_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpost',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
