# Generated by Django 3.1.4 on 2020-12-06 15:08

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20201205_2134'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modelpost',
            managers=[
                ('issued', django.db.models.manager.Manager()),
            ],
        ),
    ]
