# Generated by Django 3.1.4 on 2021-01-01 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_modelpost_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpost',
            name='slug',
        ),
        migrations.AlterField(
            model_name='modelpost',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
