# Generated by Django 3.1.4 on 2021-01-01 21:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('post', '0006_auto_20210101_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
